spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simple_mooc?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  #.yml
  logging:
    config: classpath:logback-spring.xml

  jwt:
    secret: gUM+BALaPCW3O1VDxasOL26CNITirSV11zoWFeqT1mqfp9VuX3tFX2J60nGZDslIdKHfNUHPMJuR+PJZ+B3M2w==
